name: CI/CD for Python on Firebase

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) python -m unittest discover -s tests
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Deploy only from the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
      - name: Authenticate Firebase with Service Account
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
#Create a temporary file for the Firebase service account JSON key
          echo "$FIREBASE_CREDENTIALS" > $HOME/firebase-service-account.json
      # Set the GOOGLE_APPLICATION_CREDENTIALS environment variable for Firebase CLI
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
      # Authenticate Firebase CLI using the service account
          firebase use --add  # This will automatically use the correct Firebase project
      # Step 5: Deploy to Firebase Hosting
      # - name: Authenticate with Firebase
      #   env:
      #     FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      #   run: |
      #     echo $FIREBASE_SERVICE_ACCOUNT > $HOME/firebase-key.json
      #     gcloud auth activate-service-account --key-file=$HOME/firebase-key.json
      #     gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
