name: CI/CD for Python on Firebase
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Unit Tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) python -m unittest discover -s tests
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Deploy only from the main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
      # Authenticate with Firebase using the service account JSON key
      - name: Authenticate Firebase with Service Account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  # Secret containing Firebase service account JSON key
        run: |
# Save the service account key to a file
          echo "$FIREBASE_SERVICE_ACCOUNT" > $HOME/firebase-service-account.json
          # Set the GOOGLE_APPLICATION_CREDENTIALS environment variable for Firebase CLI
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
          # Authenticate with Firebase
          firebase use --add  # This will automatically set up the correct Firebase project for the deployment
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting