name: Firebase Hosting Deployment for Merge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      # Step 1: Checkout the repository

      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Set up Node.js (you can keep the version as per your project)

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Step 3: Install Firebase CLI globally

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      # Step 4: Authenticate with Firebase using the service account credentials

      - name: Authenticate Firebase with Service Account
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
#Create a temporary file for the Firebase service account JSON key
          echo "$FIREBASE_CREDENTIALS" > $HOME/firebase-service-account.json
      # Set the GOOGLE_APPLICATION_CREDENTIALS environment variable for Firebase CLI
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
      # Authenticate Firebase CLI using the service account
          firebase use --add  # This will automatically use the correct Firebase project
      # Step 5: Deploy to Firebase Hosting
      
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting